import { useState } from "react";
import { Download, Bell, CheckCircle } from "lucide-react";

const pageConfig = {
  "dashboard":  { eyebrow: "Overview",        title: "Career command center" },
  "career-map": { eyebrow: "Journey",          title: "Your career map"       },
  "resume":     { eyebrow: "Resume",           title: "Resume intelligence"   },
  "network":    { eyebrow: "Connections",      title: "Network strategy"      },
  "companies":  { eyebrow: "Target companies", title: "Company research"      },
};

function exportCareerPlan(target, pathScore) {
  const date = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
  const lines = [
    "PathForge — Career Intelligence Export",
    `Generated: ${date}`,
    "",
    "═══════════════════════════════════════",
    `TARGET: ${target.role} at ${target.company}`,
    `PATH SCORE: ${pathScore}/100`,
    "═══════════════════════════════════════",
    "",
    "CAREER ROUTE",
    "───────────────────────────────────────",
    ...target.nodes.map(
      (n, i) => `Step ${i + 1} — ${n.label}: ${n.title} (${n.match}% fit · ${n.timeframe})`
    ),
    "",
    "PRIORITY ACTIONS",
    "───────────────────────────────────────",
    ...target.nextMoves.map((m, i) => `${i + 1}. ${m}`),
    "",
    "RESUME FOCUS",
    "───────────────────────────────────────",
    target.resumeGap?.focus ?? "Update your resume with EV-specific achievements.",
    "",
    "KEYWORDS TO ADD",
    "───────────────────────────────────────",
    (target.resumeGap?.missingKeywords ?? []).join(", "),
    "",
    "TARGET COMPANIES",
    "───────────────────────────────────────",
    ...target.companies.map((c) => `• ${c.name} — ${c.fit}`),
    "",
    "═══════════════════════════════════════",
    "Generated by PathForge · pathforge.app",
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `pathforge-${target.company.toLowerCase().replace(/\s+/g, "-")}-plan.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function Header({ page, target, pathScore }) {
  const config = pageConfig[page] ?? pageConfig["dashboard"];
  const [bellActive, setBellActive] = useState(false);
  const [exported, setExported] = useState(false);

  function handleBell() {
    setBellActive(true);
    setTimeout(() => setBellActive(false), 2200);
  }

  function handleExport() {
    if (!target) return;
    exportCareerPlan(target, pathScore ?? target.score);
    setExported(true);
    setTimeout(() => setExported(false), 2000);
  }

  return (
    <header className="header">
      <div className="headerLeft">
        <p className="eyebrow">{config.eyebrow}</p>
        <h1>{config.title}</h1>
      </div>

      <div className="headerRight">
        <div style={{ position: "relative" }}>
          <button
            className={`headerBtn headerBtn-ghost ${bellActive ? "headerBtn-active" : ""}`}
            type="button"
            onClick={handleBell}
            title="Notifications"
            style={{ transition: "all 0.2s" }}
          >
            <Bell size={15} />
          </button>
          {bellActive && (
            <div style={{
              position: "absolute", top: "calc(100% + 8px)", right: 0,
              background: "var(--s3)", border: "1px solid var(--border-sage)",
              borderRadius: "var(--r-lg)", padding: "10px 14px",
              fontSize: "0.78rem", fontWeight: 600, color: "var(--sage-lt)",
              whiteSpace: "nowrap", zIndex: 50,
              animation: "scaleIn 0.18s var(--ease) both",
            }}>
              ✓ You're on track — keep going
            </div>
          )}
        </div>

        <button
          className={`headerBtn ${exported ? "headerBtn-sage" : "headerBtn-primary"}`}
          type="button"
          onClick={handleExport}
          title="Download your career plan as a text file"
        >
          {exported ? <CheckCircle size={14} /> : <Download size={14} />}
          {exported ? "Exported!" : "Export plan"}
        </button>
      </div>
    </header>
  );
}
